### ISSUE TITLE
Default file is development.json and default directory is "." 

### ISSUE THREAD

**Issue by vinayathimmappa** [electrode-io/electrode-confippet#15]
I am using  "electrode-confippet": "^1.5.0" and i am seeing that 

- default directory is current directorynot config directory (document says default directory is config) 
-Default file is default.json, but i am seeing development.json is being taken as the default directory.

I think this is a bug on documentation , that needs to be fixed

**Comment by jchip** [comment]
default directory is `config` and the preset config composition rules is documented here https://github.com/electrode-io/electrode-confippet#config-composition.

Note that you can change all of these.  

You can define your own composition rules.

If you have examples that shows the behavior you are seeing, please post them.
