### ISSUE TITLE
Union merging arrays?

### ISSUE THREAD

**Issue by wmertens** [electrode-io/electrode-confippet#16]
I tried using union merge on an array by prepending `+` to the key, but it turns out that both the source and the target array need to have the `+` in the key name. That is surprising. Should it not be possible to append to arrays without requiring the original array key to start with a `+`?

I also noticed that there are still several calls to `util.merge` instead of `util.uMerge` in the code, and I wonder if that is correct?

**Comment by jchip** [comment]
`+` is part of the key name.  confippet is just doing a little extra if the key name starts with `+`.

It's been a while, but the `merge` and `uMerge` should be working as expected.  If you have more specific findings, please open a new issue with that.  thanks.

**Comment by wmertens** [comment]
Yes, I understand that that's the mechanism now, but it is surprising that
plugin authors have to change all their array names to + so they can be
added to…

With _.mergeDeep it is easy to make a visitor that looks at the keyname and
merges into an array without the +…
