### ISSUE TITLE
Mention node-config?

### ISSUE THREAD

**Issue by wmertens** [electrode-io/electrode-confippet#7]
Maybe I'm overstepping some bounds here, and I really appreciate Walmart open-sourcing Electrode, but shouldn't this project mention https://github.com/lorenwest/node-config in thanks for the obvious inspiration?

I have no stakes here, in fact I'm very deeply looking into replacing my home grown solution with Electrode because I was doing the same thing (configuration over code, remove all possible boilerplate).

**Comment by jchip** [comment]
Right, I used to directly reference node-config in the README for the default config files structure that's intentionally made to be the same as node-config.  https://github.com/electrode-io/electrode-confippet/blob/f123f39bcbce9283aded6faef05f4b1e6cc3009f/README.md#default-config-files-settings

The README was rewritten and that reference was lost.

**Comment by ananavati** [comment]
@wmertens can we please close out on this issue now that a reference to `node-config` has been re-added to the README as part of this pr https://github.com/electrode-io/electrode-confippet/pull/9

**Comment by wmertens** [comment]
:+1:
